import {inject, Injectable} from '@angular/core';
import {SwUpdate} from '@angular/service-worker';
import pTimeout, {TimeoutError} from 'p-timeout';

import {BUILD_TIMESTAMP} from '../../environments/build-version';

/**
 * Upper bound for the download step on the /updating page. Covers slow
 * mobile networks; beyond this we force a reload anyway — either the new
 * SW is already in `waiting` and the reload will activate it, or the
 * next navigation retries from scratch.
 */
const DOWNLOAD_TIMEOUT_MS = 30_000;

/**
 * Two-phase PWA update strategy.
 *
 * Angular's native `SwUpdate.checkForUpdate()` bundles three things in a
 * single call: it fetches `ngsw.json`, detects a new version, *and*
 * pre-fetches every hashed asset listed in `assetGroups` into Cache
 * Storage — there is no `{ downloadAssets: false }` knob. On slow mobile
 * networks that download is the expensive part and can make the app feel
 * sluggish for several seconds if triggered silently during login.
 *
 * We therefore split the cycle in two:
 *
 *  1. DETECT — `hasUpdate()` does a tiny fetch of `/version.json` from
 *     the origin (bypassing every cache layer — see the inline notes in
 *     the method) and compares its `timestamp` field with
 *     `BUILD_TIMESTAMP` baked into this bundle at build time via
 *     `fileReplacements` in angular.json. Both values are produced by
 *     the same `prebuild` script from a single `Date.now()` call so
 *     they're guaranteed equal within a build. No asset download
 *     happens here. Callers use this at sign-in and on session resume
 *     to decide whether to route to /updating.
 *
 *  2. DOWNLOAD — `download()` calls `SwUpdate.checkForUpdate()`, which
 *     fetches the new `ngsw.json` and pre-loads every hashed asset into
 *     Cache Storage, leaving the new SW in the `waiting` state. This is
 *     the network-heavy step and runs on the /updating page so the
 *     animated splash is already visible throughout.
 *
 *  3. RELOAD — `reload()` navigates to `/`. The browser then hands over
 *     to the waiting SW on the fresh page load. We deliberately skip
 *     `SwUpdate.activateUpdate()` because the Angular team warns it can
 *     desync in-memory code with newly-cached assets — a full reload is
 *     the clean way.
 *
 * Why `BUILD_TIMESTAMP` and not the Angular APIs: Angular doesn't expose
 * a detect-only check, and `SwUpdate.versionUpdates` only emits while a
 * check is in flight — we'd miss events that fired before the first
 * subscription on cold start. Comparing a constant baked into our own
 * bundle against our own `/version.json` is stateless, deterministic
 * and survives every reload / tab close / cold start by construction.
 */
@Injectable({
  providedIn: 'root',
})
export class PwaUpdateService {

  private readonly swUpdate = inject(SwUpdate);

  /**
   * Returns true when the server-side `/version.json` timestamp differs
   * from the `BUILD_TIMESTAMP` embedded in this running bundle. Conservative:
   * any network/parse error returns false so a degraded check never
   * blocks the user on /updating.
   *
   * Dev builds short-circuit on `swUpdate.isEnabled === false`, which
   * Angular sets from `environment.production` in app.config.ts.
   */
  async hasUpdate(budgetMs: number): Promise<boolean> {
    if (!this.swUpdate.isEnabled) {
      return false;
    }
    const remote = await this.fetchRemoteTimestamp(budgetMs);
    return remote !== null && remote !== BUILD_TIMESTAMP;
  }

  /**
   * Fetches `/version.json` from the origin and returns its `timestamp`
   * field, or `null` on any network/parse failure.
   *
   * This file is generated by `scripts/write-build-version.ts` in the
   * same tick that sets `BUILD_TIMESTAMP`, so the two values are equal
   * by construction within a given build — that equality is what
   * `hasUpdate()` relies on to avoid a redirect loop to /updating.
   *
   * Three defenses stack to ensure the GET always reaches the origin
   * server, regardless of what any cache layer has decided to do:
   *   1. `ngsw-bypass=true` — Angular SW honours this query string and
   *      lets the request hit the network instead of serving its cached
   *      copy.
   *   2. `cb=<ts>` — unique URL per call, neutralises browser/CDN/proxy
   *      HTTP caches that might otherwise return a cached response.
   *   3. `cache: 'no-store'` — tells the browser neither to read from
   *      nor write to its HTTP cache for this request.
   */
  private async fetchRemoteTimestamp(budgetMs: number): Promise<number | null> {
    try {
      const response = await fetch(`/version.json?ngsw-bypass=true&cb=${Date.now()}`, {
        cache: 'no-store',
        signal: AbortSignal.timeout(budgetMs),
      });
      if (!response.ok) {
        return null;
      }
      const payload = await response.json() as {timestamp?: number};
      return typeof payload.timestamp === 'number' ? payload.timestamp : null;
    } catch (error) {
      console.error('hasUpdate check failed', error);
      return null;
    }
  }

  /**
   * Triggers the SW to download and install the new version into its
   * `waiting` slot, bounded by a timeout. We deliberately do NOT call
   * `swUpdate.activateUpdate()`: the Angular team advises against it
   * because swapping the active SW while the current page is still
   * running can mismatch in-memory code with newly-cached assets. The
   * clean way is to let the caller reload — the browser then picks up
   * the waiting SW naturally on the fresh navigation.
   *
   * Any failure is logged and swallowed; the caller reloads regardless.
   */
  async download(): Promise<void> {
    try {
      await pTimeout(this.swUpdate.checkForUpdate(), {
        milliseconds: DOWNLOAD_TIMEOUT_MS,
        message: 'SW checkForUpdate timed out',
      });
    } catch (error) {
      if (error instanceof TimeoutError) {
        console.error('SW download hung, forcing reload', error);
      } else {
        console.error('Failed to download SW update', error);
      }
    }
  }

  /**
   * Forces a full page reload so the browser picks up the newly activated
   * Service Worker and its fresh assets. `location.replace('/')` overwrites
   * the `/updating` history entry instead of pushing on top of it, so a
   * browser back-gesture after the update doesn't land the user on the
   * updating screen again and re-trigger the whole flow.
   *
   * ngsw's worker calls `self.skipWaiting()` during install, which lets
   * the newly-downloaded SW take over immediately on this navigation
   * without waiting for every tab to close.
   */
  reload(): void {
    location.replace('/');
  }
}
