/**
 * @fileoverview Server-side Lightning Service Orchestrator
 *
 * This service orchestrates Lightning Network operations by delegating to
 * specialized services. It provides a unified server-side interface while
 * maintaining single responsibility for each operation type.
 *
 * Key Features:
 * - Orchestrates specialized Lightning services (invoice generation, status monitoring, etc.)
 * - Provides unified initialization and health checking
 * - Maintains backward compatibility with existing API
 * - Delegates to focused, testable service modules
 * - Handles Lightning Network Bitcoin payments that get swapped to Starknet assets
 *
 * Flow:
 * 1. User requests Lightning invoice for specified amount
 * 2. Delegates to LightningInvoiceGenerator via Atomiq SDK
 * 3. QR code generated by QRCodeGenerator service
 * 4. Status monitored via LightningStatusMonitor
 * 5. Completion handled through SwapOrchestrator
 *
 * @requires ./lightning - Specialized Lightning service modules
 * @requires ./atomiq - Atomiq SDK service
 * @requires ./lightning-limits.service - Lightning limits service
 *
 * @author bim
 * @version 2.0.0
 */

import { LightningError, LightningErrors } from '$lib/errors/lightning';
import { logger } from '$lib/utils/logger';
import { monitoring } from '$lib/utils/monitoring';
import { getAtomiqService } from './atomiq';
import { lightningLimits } from './lightning-limits.service';

// Import specialized services
import {
	LightningInvoiceGenerator,
	LightningQuoteService,
	LightningStatusMonitor,
	LightningSwapOrchestrator,
	QRCodeGenerator
} from './lightning';

// Import types from centralized location
import type {
	CreateLightningPaymentOptions,
	CreateStarknetToLightningSwapOptions,
	LightningInvoice,
	StarknetToLightningSwap,
	SwapStatus
} from '$lib/types/lightning';

/**
 * Re-export types for backward compatibility
 */
export type {
	CreateLightningPaymentOptions,
	CreateStarknetToLightningSwapOptions,
	LightningInvoice,
	StarknetToLightningSwap,
	SwapStatus
};

/**
 * Server-side Lightning Service Orchestrator
 *
 * Handles Lightning Bitcoin payments and cross-chain swaps to Starknet
 * using specialized services and the Atomiq SDK.
 */
export class LightningService {
	private static instance: LightningService;
	private swapperInitialized = false;

	// Specialized service instances
	private invoiceGenerator: LightningInvoiceGenerator;
	private swapOrchestrator: LightningSwapOrchestrator;
	private statusMonitor: LightningStatusMonitor;
	private quoteService: LightningQuoteService;
	private qrCodeGenerator: QRCodeGenerator;

	private constructor() {
		// Initialize specialized services
		this.invoiceGenerator = new LightningInvoiceGenerator();
		this.swapOrchestrator = new LightningSwapOrchestrator();
		this.statusMonitor = new LightningStatusMonitor();
		this.quoteService = new LightningQuoteService();
		this.qrCodeGenerator = new QRCodeGenerator();

		logger.info('Lightning Service orchestrator initialized with specialized services');
	}

	/**
	 * Get singleton instance of LightningService
	 */
	static getInstance(): LightningService {
		if (!LightningService.instance) {
			LightningService.instance = new LightningService();
		}
		return LightningService.instance;
	}

	// ========================================
	// Initialization and Health Management
	// ========================================

	/**
	 * Initialize the Lightning service and all specialized services
	 *
	 * This method sets up the Atomiq SDK connection and verifies
	 * that Lightning Network functionality is available.
	 */
	async initialize(): Promise<void> {
		try {
			logger.info('🔧 Lightning service initialization started');

			// Initialize core dependencies first
			logger.info('🔧 Initializing Atomiq SDK...');
			await getAtomiqService().initialize();
			logger.info('🔧 Atomiq SDK initialized successfully');

			// Lightning limits service doesn't need initialization - it's stateless
			logger.info('🔧 Lightning limits service ready (no initialization needed)');

			// Initialize specialized services
			logger.info('🔧 Initializing specialized Lightning services...');
			await Promise.all([this.invoiceGenerator.initialize(), this.statusMonitor.initialize()]);
			logger.info('🔧 All specialized Lightning services initialized successfully');

			this.swapperInitialized = true;
			logger.info('🔧 Lightning service fully initialized');

			// Track successful initialization
			monitoring.incrementCounter('lightning_service_initialized');
		} catch (error) {
			logger.error('Failed to initialize Lightning service', error as Error);
			monitoring.incrementCounter('lightning_service_initialization_failed');
			throw LightningErrors.initializationFailed('Failed to initialize Lightning service', {
				originalError: error as Error
			});
		}
	}

	/**
	 * Check if Lightning service is properly initialized
	 */
	isInitialized(): boolean {
		return this.swapperInitialized;
	}

	/**
	 * Health check for Lightning service and all specialized services
	 */
	async healthCheck(): Promise<{
		status: 'healthy' | 'unhealthy';
		services: Record<string, boolean>;
		dependencies: Record<string, boolean>;
		timestamp: string;
	}> {
		const serviceResults = {
			invoiceGenerator: false,
			swapOrchestrator: false,
			statusMonitor: false,
			quoteService: false,
			qrCodeGenerator: false
		};

		const dependencyResults = {
			atomiqService: false,
			lightningLimits: false,
			initialization: this.swapperInitialized
		};

		try {
			// Check core dependencies
			dependencyResults.atomiqService = await getAtomiqService().healthCheck();
			dependencyResults.lightningLimits = await lightningLimits.healthCheck();

			// Check specialized services
			const serviceChecks = await Promise.allSettled([
				this.invoiceGenerator.healthCheck(),
				this.swapOrchestrator.healthCheck(),
				this.statusMonitor.healthCheck(),
				this.quoteService.healthCheck(),
				this.qrCodeGenerator.healthCheck()
			]);

			serviceResults.invoiceGenerator =
				serviceChecks[0].status === 'fulfilled' && serviceChecks[0].value;
			serviceResults.swapOrchestrator =
				serviceChecks[1].status === 'fulfilled' && serviceChecks[1].value;
			serviceResults.statusMonitor =
				serviceChecks[2].status === 'fulfilled' && serviceChecks[2].value;
			serviceResults.quoteService =
				serviceChecks[3].status === 'fulfilled' && serviceChecks[3].value;
			serviceResults.qrCodeGenerator =
				serviceChecks[4].status === 'fulfilled' && serviceChecks[4].value;
		} catch (error) {
			logger.warn('Lightning Service: Health check encountered errors', error as Error);
		}

		const allServicesHealthy = Object.values(serviceResults).every((healthy) => healthy);
		const allDependenciesHealthy = Object.values(dependencyResults).every((healthy) => healthy);
		const overallHealthy = allServicesHealthy && allDependenciesHealthy;

		return {
			status: overallHealthy ? 'healthy' : 'unhealthy',
			services: serviceResults,
			dependencies: dependencyResults,
			timestamp: new Date().toISOString()
		};
	}

	// ========================================
	// Invoice Operations (delegate to LightningInvoiceGenerator)
	// ========================================

	/**
	 * Create a Lightning invoice for Bitcoin to Starknet swap
	 */
	async createLightningPayment(options: CreateLightningPaymentOptions): Promise<LightningInvoice> {
		this.ensureInitialized();

		const startTime = Date.now();

		try {
			logger.info('Lightning Service: Creating Lightning payment via InvoiceGenerator', options);

			const result = await this.invoiceGenerator.createLightningPayment(options);

			// Track success metrics
			monitoring.trackOperationTime('lightning_create_payment', Date.now() - startTime);
			monitoring.incrementCounter('lightning_payment_created');

			return result;
		} catch (error) {
			monitoring.incrementCounter('lightning_payment_creation_failed');
			logger.error('Lightning Service: Payment creation failed', error as Error, options);
			throw error;
		}
	}

	// ========================================
	// Status Operations (delegate to LightningStatusMonitor)
	// ========================================

	/**
	 * Get swap status for a Lightning swap
	 */
	async getSwapStatus(swapId: string): Promise<SwapStatus> {
		await this.ensureInitialized();

		const startTime = Date.now();

		try {
			logger.info('Lightning Service: Getting swap status via StatusMonitor', {
				swapId
			});

			const result = await this.statusMonitor.getSwapStatus(swapId);

			// Track success metrics
			monitoring.trackOperationTime('lightning_get_swap_status', Date.now() - startTime);

			return result;
		} catch (error) {
			monitoring.incrementCounter('lightning_swap_status_failed');
			logger.error('Lightning Service: Swap status retrieval failed', error as Error, { swapId });
			throw error;
		}
	}

	/**
	 * Update swap status
	 */
	async updateSwapStatus(swapId: string, statusUpdate: any): Promise<void> {
		await this.ensureInitialized();

		try {
			logger.info('Lightning Service: Updating swap status via StatusMonitor', {
				swapId,
				statusUpdate
			});

			return this.statusMonitor.updateSwapStatus(swapId, statusUpdate);
		} catch (error) {
			monitoring.incrementCounter('lightning_swap_status_update_failed');
			logger.error('Lightning Service: Swap status update failed', error as Error, { swapId });
			throw error;
		}
	}

	// ========================================
	// Quote Operations (delegate to LightningQuoteService)
	// ========================================

	/**
	 * Get quote for Lightning swap
	 */
	async getLightningQuote(amount: number, destinationAsset?: string): Promise<any> {
		this.ensureInitialized();

		const startTime = Date.now();

		try {
			logger.info('Lightning Service: Getting quote via QuoteService', {
				amount,
				destinationAsset
			});

			const result = await this.quoteService.getQuote(amount, destinationAsset);

			// Track success metrics
			monitoring.trackOperationTime('lightning_get_quote', Date.now() - startTime);

			return result;
		} catch (error) {
			monitoring.incrementCounter('lightning_quote_failed');
			logger.error('Lightning Service: Quote retrieval failed', error as Error, {
				amount,
				destinationAsset
			});
			throw error;
		}
	}

	// ========================================
	// Starknet to Lightning Operations (delegate to LightningSwapOrchestrator)
	// ========================================

	/**
	 * Create Starknet to Lightning swap
	 */
	async createStarknetToLightningSwap(
		options: CreateStarknetToLightningSwapOptions
	): Promise<StarknetToLightningSwap> {
		this.ensureInitialized();

		const startTime = Date.now();

		try {
			logger.info(
				'Lightning Service: Creating Starknet to Lightning swap via SwapOrchestrator',
				options
			);

			const result = await this.swapOrchestrator.createStarknetToLightningSwap(options);

			// Track success metrics
			monitoring.trackOperationTime(
				'lightning_create_starknet_to_lightning',
				Date.now() - startTime
			);
			monitoring.incrementCounter('lightning_starknet_to_lightning_created');

			return result;
		} catch (error) {
			monitoring.incrementCounter('lightning_starknet_to_lightning_failed');
			logger.error(
				'Lightning Service: Starknet to Lightning swap creation failed',
				error as Error,
				options
			);
			throw error;
		}
	}

	// ========================================
	// QR Code Operations (delegate to QRCodeGenerator)
	// ========================================

	/**
	 * Generate QR code for Lightning invoice
	 */
	async generateQRCode(invoice: string): Promise<string> {
		const startTime = Date.now();

		try {
			logger.info('Lightning Service: Generating QR code via QRCodeGenerator');

			const result = await this.qrCodeGenerator.generateQRCode(invoice);

			// Track success metrics
			monitoring.trackOperationTime('lightning_generate_qr', Date.now() - startTime);

			return result;
		} catch (error) {
			monitoring.incrementCounter('lightning_qr_generation_failed');
			logger.error('Lightning Service: QR code generation failed', error as Error, { invoice });
			throw error;
		}
	}

	// ========================================
	// Limits and Validation (delegate to existing services)
	// ========================================

	/**
	 * Get Lightning swap limits
	 */
	async getLimits(): Promise<any> {
		await this.ensureInitialized();

		try {
			logger.info('Lightning Service: Getting limits via lightningLimits service');
			return await lightningLimits.getLimits();
		} catch (error) {
			logger.error('Lightning Service: Limits retrieval failed', error as Error);
			throw error;
		}
	}

	/**
	 * Validate Lightning payment parameters
	 */
	validateLightningPayment(options: CreateLightningPaymentOptions): void {
		logger.info(
			'Lightning Service: Validating payment parameters via lightningLimits service',
			options
		);
		lightningLimits.validateLightningPayment(options);
	}

	// ========================================
	// Private Helper Methods
	// ========================================

	/**
	 * Ensure the service is initialized before processing requests
	 */
	private async ensureInitialized(): Promise<void> {
		if (!this.swapperInitialized) {
			logger.info('Lightning service not initialized, auto-initializing...');
			try {
				await this.initialize();
			} catch (error) {
				logger.error('Failed to auto-initialize Lightning service', error as Error);
				monitoring.incrementCounter('lightning_service_auto_init_failed');
				throw LightningErrors.initializationFailed('Failed to auto-initialize Lightning service', {
					originalError: error as Error
				});
			}
		}
	}
}

/**
 * Factory function to get singleton instance without build-time initialization
 */
export const getLightningService = (): LightningService => {
	return LightningService.getInstance();
};
