/**
 * Domain error codes.
 * Used for i18n lookup on the frontend and for structured API error responses.
 */
export const ErrorCode = {
  // Generic
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',

  // Auth
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  ACCOUNT_ALREADY_EXISTS: 'ACCOUNT_ALREADY_EXISTS',
  INVALID_USERNAME: 'INVALID_USERNAME',
  CHALLENGE_NOT_FOUND: 'CHALLENGE_NOT_FOUND',
  CHALLENGE_EXPIRED: 'CHALLENGE_EXPIRED',
  CHALLENGE_ALREADY_USED: 'CHALLENGE_ALREADY_USED',
  INVALID_CHALLENGE: 'INVALID_CHALLENGE',
  AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILED',
  REGISTRATION_FAILED: 'REGISTRATION_FAILED',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_EXPIRED: 'SESSION_EXPIRED',

  // Account
  ACCOUNT_NOT_DEPLOYED: 'ACCOUNT_NOT_DEPLOYED',
  INVALID_ACCOUNT_STATE: 'INVALID_ACCOUNT_STATE',
  ACCOUNT_DEPLOYMENT_FAILED: 'ACCOUNT_DEPLOYMENT_FAILED',
  INVALID_STARKNET_ADDRESS: 'INVALID_STARKNET_ADDRESS',

  // Swap
  SWAP_NOT_FOUND: 'SWAP_NOT_FOUND',
  SWAP_EXPIRED: 'SWAP_EXPIRED',
  SWAP_AMOUNT_OUT_OF_RANGE: 'SWAP_AMOUNT_OUT_OF_RANGE',
  SWAP_CREATION_FAILED: 'SWAP_CREATION_FAILED',
  INVALID_SWAP_STATE: 'INVALID_SWAP_STATE',

  // Payment
  BUILD_EXPIRED: 'BUILD_EXPIRED',
  FORBIDDEN: 'FORBIDDEN',
  PAYMENT_PARSING_ERROR: 'PAYMENT_PARSING_ERROR',
  INVALID_PAYMENT_AMOUNT: 'INVALID_PAYMENT_AMOUNT',
  SAME_ADDRESS_PAYMENT: 'SAME_ADDRESS_PAYMENT',
  UNSUPPORTED_NETWORK: 'UNSUPPORTED_NETWORK',
  UNSUPPORTED_TOKEN: 'UNSUPPORTED_TOKEN',
  INVALID_LIGHTNING_INVOICE: 'INVALID_LIGHTNING_INVOICE',
  LIGHTNING_INVOICE_EXPIRED: 'LIGHTNING_INVOICE_EXPIRED',
  INVALID_BITCOIN_ADDRESS: 'INVALID_BITCOIN_ADDRESS',
  BITCOIN_ADDRESS_NETWORK_MISMATCH: 'BITCOIN_ADDRESS_NETWORK_MISMATCH',
  INVALID_PAYMENT_ADDRESS: 'INVALID_PAYMENT_ADDRESS',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  INSUFFICIENT_BALANCE_WITH_AMOUNT: 'INSUFFICIENT_BALANCE_WITH_AMOUNT',
  INSUFFICIENT_BALANCE_SECURITY_DEPOSIT: 'INSUFFICIENT_BALANCE_SECURITY_DEPOSIT',

  // User
  USER_SETTINGS_NOT_FOUND: 'USER_SETTINGS_NOT_FOUND',
  UNSUPPORTED_CURRENCY: 'UNSUPPORTED_CURRENCY',

  // External services
  EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
  PAYMASTER_SERVICE_ERROR: 'PAYMASTER_SERVICE_ERROR',
  TIMEOUT_ERROR: 'TIMEOUT_ERROR',

  // Rate limiting
  RATE_LIMITED: 'RATE_LIMITED',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
