/**
 * Writes two files from a single `Date.now()` call so both sides of the
 * PWA update check compare against the exact same value:
 *
 *   1. `src/environments/build-version.prod.ts` — baked into the JS
 *      bundle via Angular `fileReplacements` (angular.json). Read at
 *      runtime as the "my version" side of the comparison.
 *
 *   2. `public/version.json` — copied verbatim into `dist/` by Angular
 *      as a static asset. Fetched at runtime as the "server version"
 *      side of the comparison.
 *
 * Runs automatically via the `prebuild` npm hook before every production
 * / testnet `ng build`. Using Angular's own `ngsw.json.timestamp` as the
 * server side would desync — Angular computes it a few seconds after
 * this script runs and the two values would never match, causing an
 * infinite redirect loop to /updating.
 */
import {writeFileSync} from 'node:fs';

// Relative paths, resolved by Node against the current working directory.
// npm always invokes scripts with cwd set to the package containing the
// `prebuild` hook (apps/front here).
const BUILD_VERSION_PATH = 'src/environments/build-version.prod.ts';
const VERSION_JSON_PATH = 'public/version.json';
const timestamp = Date.now();

const tsSource = `// Generated by scripts/write-build-version.ts — do not edit by hand.
export const BUILD_TIMESTAMP = ${timestamp};
`;

const jsonSource = `${JSON.stringify({timestamp})}\n`;

writeFileSync(BUILD_VERSION_PATH, tsSource);
writeFileSync(VERSION_JSON_PATH, jsonSource);
console.log(`[build-version] wrote ${BUILD_VERSION_PATH} + ${VERSION_JSON_PATH} (timestamp = ${timestamp})`);
